#spring.application.name=demoSpringJpaCrud
#spring.datasource.url=jdbc:sqlserver://DESKTOP-8CJLOIL\SQLEXPRESS:1433;databaseName=telsuko;encrypt=false;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=rikka
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#
#
## Hibernate (Optional)
#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
#spring.jpa.hibernate.ddl-auto=update


#spring.datasource.url=jdbc:postgresql://localhost:5432/testingdb
#spring.datasource.username=postgres
#spring.datasource.password=rikka
#spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate settings
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# SQL Server Database Connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=testingdb;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=mondi
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Connection Pool Settings (Optional, for performance tuning)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# JPA (If Using JPA, Otherwise Ignore)
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


